"""Add 2 items HistoricData

Revision ID: 0802c80846e9
Revises: e9c12cdb44ce
Create Date: 2023-09-24 20:12:40.049541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0802c80846e9'
down_revision = 'e9c12cdb44ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_log')
    op.add_column('historic', sa.Column('min_depth', sa.String(), nullable=True))
    op.add_column('historic', sa.Column('max_depth', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historic', 'max_depth')
    op.drop_column('historic', 'min_depth')
    op.create_table('user_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('image_file', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
