"""Add selected_items column

Revision ID: 58596a7a2414
Revises: 5060f18b083e
Create Date: 2023-08-16 11:43:00.822647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58596a7a2414'
down_revision = '5060f18b083e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_data', sa.Column('selected_vars', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('input_data', 'selected_vars')
    # ### end Alembic commands ###
