"""Add cols to HistoricData

Revision ID: e9c12cdb44ce
Revises: 470eb904b397
Create Date: 2023-08-29 15:31:30.385962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c12cdb44ce'
down_revision = '470eb904b397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historic', sa.Column('lgth_last_elem', sa.Integer(), nullable=True))
    op.drop_column('historic', 'var1_dtw')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historic', sa.Column('var1_dtw', sa.VARCHAR(), nullable=True))
    op.drop_column('historic', 'lgth_last_elem')
    # ### end Alembic commands ###
